import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Utils/Header.js";
import Footer from "./Utils/Footer.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Encoderbytes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
